# Домашнее задание № 1

Датасет содержит информацию о расходах на рекламу в различных медиа-каналах и соответствующих им результатах продаж.

Датасет состоит из табличных данных, где каждая строка представляет отдельное наблюдение кампании. Датасет включает следующие независимые переменные (признаки):​

* `TV` — объём расходов на телевизионную рекламу (в тысячах долларов)

* `Radio` — объём расходов на радиорекламу (в тысячах долларов)

* `Newspaper` — объём расходов на газетную рекламу (в тысячах долларов)

Зависимая переменная (целевая переменная):

* `Sales` — объём продаж, достигнутый после рекламной кампании

**Задание** : 
1. Проверьте наличие линейной взаимосвязи через ранг матрицы
2. Реализуйте прогностическую модель для объема продаж на основе остальных признаков
3. Сравните классический подход (вручную перемножая матрицы), с заменой обратной матрицы на псевдо-обратную и через готовый класс из библиотеки `scikit-learn`.
4.  Оцените качество в каждом случае. Проинтерпретируйте полученный результат.

In [1]:
import pandas as pd
df = pd.read_csv('Advertising.csv')

In [2]:
# ТУТ И ДАЛЕЕ ВАШ КОД

In [3]:
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.isnull().sum()

Unnamed: 0    0
TV            0
radio         0
newspaper     0
sales         0
dtype: int64

In [5]:
import numpy as np

**Задание 1. Проверьте наличие линейной взаимосвязи через ранг матрицы.**

In [6]:
# проверяем наличие линейной взаимосвязи по первому заданию
np.linalg.matrix_rank(df)

np.int64(5)

In [7]:
df.shape

(200, 5)

Вывод по заданию 1: Наличия линейной взаимосвязи между признаками нет.

**Задание 2. Реализуйте прогностическую модель для объема продаж на основе остальных признаков.**

In [8]:
df.corr()

            Unnamed: 0        TV     radio  newspaper     sales
Unnamed: 0    1.000000  0.017715 -0.110680  -0.154944 -0.051616
TV            0.017715  1.000000  0.054809   0.056648  0.782224
radio        -0.110680  0.054809  1.000000   0.354104  0.576223
newspaper    -0.154944  0.056648  0.354104   1.000000  0.228299
sales        -0.051616  0.782224  0.576223   0.228299  1.000000

In [9]:
df.columns

Index(['Unnamed: 0', 'TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [10]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [11]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [12]:
df.corr()

                 TV     radio  newspaper     sales
TV         1.000000  0.054809   0.056648  0.782224
radio      0.054809  1.000000   0.354104  0.576223
newspaper  0.056648  0.354104   1.000000  0.228299
sales      0.782224  0.576223   0.228299  1.000000

In [13]:
df.shape

(200, 4)

In [14]:
np.linalg.matrix_rank(df)

np.int64(4)

In [15]:
np.linalg.det(df.T@df)

np.float64(2.9296719391086264e+19)

In [16]:
np.linalg.det(df.corr())

np.float64(0.0894880484545735)

In [17]:
y = df['sales']
X = df.drop('sales', axis=1)

**Классический подход**

In [18]:
X

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [19]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [20]:
X.corr()

                 TV     radio  newspaper
TV         1.000000  0.054809   0.056648
radio      0.054809  1.000000   0.354104
newspaper  0.056648  0.354104   1.000000

In [21]:
X.shape[0]

200

In [22]:
n = X.shape[0]
X = np.column_stack((np.ones(n), X))

In [28]:
X

array([[  1. , 230.1,  37.8,  69.2],
       [  1. ,  44.5,  39.3,  45.1],
       [  1. ,  17.2,  45.9,  69.3],
       [  1. , 151.5,  41.3,  58.5],
       [  1. , 180.8,  10.8,  58.4],
       [  1. ,   8.7,  48.9,  75. ],
       [  1. ,  57.5,  32.8,  23.5],
       [  1. , 120.2,  19.6,  11.6],
       [  1. ,   8.6,   2.1,   1. ],
       [  1. , 199.8,   2.6,  21.2],
       [  1. ,  66.1,   5.8,  24.2],
       [  1. , 214.7,  24. ,   4. ],
       [  1. ,  23.8,  35.1,  65.9],
       [  1. ,  97.5,   7.6,   7.2],
       [  1. , 204.1,  32.9,  46. ],
       [  1. , 195.4,  47.7,  52.9],
       [  1. ,  67.8,  36.6, 114. ],
       [  1. , 281.4,  39.6,  55.8],
       [  1. ,  69.2,  20.5,  18.3],
       [  1. , 147.3,  23.9,  19.1],
       [  1. , 218.4,  27.7,  53.4],
       [  1. , 237.4,   5.1,  23.5],
       [  1. ,  13.2,  15.9,  49.6],
       [  1. , 228.3,  16.9,  26.2],
       [  1. ,  62.3,  12.6,  18.3],
       [  1. , 262.9,   3.5,  19.5],
       [  1. , 142.9,  29.3,  12.6],
       [  1. , 240.1,  16.7,  22.9],
       [  1. , 248.8,  27.1,  22.9],
       [  1. ,  70.6,  16. ,  40.8],
       [  1. , 292.9,  28.3,  43.2],
       [  1. , 112.9,  17.4,  38.6],
       [  1. ,  97.2,   1.5,  30. ],
       [  1. , 265.6,  20. ,   0.3],
       [  1. ,  95.7,   1.4,   7.4],
       [  1. , 290.7,   4.1,   8.5],
       [  1. , 266.9,  43.8,   5. ],
       [  1. ,  74.7,  49.4,  45.7],
       [  1. ,  43.1,  26.7,  35.1],
       [  1. , 228. ,  37.7,  32. ],
       [  1. , 202.5,  22.3,  31.6],
       [  1. , 177. ,  33.4,  38.7],
       [  1. , 293.6,  27.7,   1.8],
       [  1. , 206.9,   8.4,  26.4],
       [  1. ,  25.1,  25.7,  43.3],
       [  1. , 175.1,  22.5,  31.5],
       [  1. ,  89.7,   9.9,  35.7],
       [  1. , 239.9,  41.5,  18.5],
       [  1. , 227.2,  15.8,  49.9],
       [  1. ,  66.9,  11.7,  36.8],
       [  1. , 199.8,   3.1,  34.6],
       [  1. , 100.4,   9.6,   3.6],
       [  1. , 216.4,  41.7,  39.6],
       [  1. , 182.6,  46.2,  58.7],
       [  1. , 262.7,  28.8,  15.9],
       [  1. , 198.9,  49.4,  60. ],
       [  1. ,   7.3,  28.1,  41.4],
       [  1. , 136.2,  19.2,  16.6],
       [  1. , 210.8,  49.6,  37.7],
       [  1. , 210.7,  29.5,   9.3],
       [  1. ,  53.5,   2. ,  21.4],
       [  1. , 261.3,  42.7,  54.7],
       [  1. , 239.3,  15.5,  27.3],
       [  1. , 102.7,  29.6,   8.4],
       [  1. , 131.1,  42.8,  28.9],
       [  1. ,  69. ,   9.3,   0.9],
       [  1. ,  31.5,  24.6,   2.2],
       [  1. , 139.3,  14.5,  10.2],
       [  1. , 237.4,  27.5,  11. ],
       [  1. , 216.8,  43.9,  27.2],
       [  1. , 199.1,  30.6,  38.7],
       [  1. , 109.8,  14.3,  31.7],
       [  1. ,  26.8,  33. ,  19.3],
       [  1. , 129.4,   5.7,  31.3],
       [  1. , 213.4,  24.6,  13.1],
       [  1. ,  16.9,  43.7,  89.4],
       [  1. ,  27.5,   1.6,  20.7],
       [  1. , 120.5,  28.5,  14.2],
       [  1. ,   5.4,  29.9,   9.4],
       [  1. , 116. ,   7.7,  23.1],
       [  1. ,  76.4,  26.7,  22.3],
       [  1. , 239.8,   4.1,  36.9],
       [  1. ,  75.3,  20.3,  32.5],
       [  1. ,  68.4,  44.5,  35.6],
       [  1. , 213.5,  43. ,  33.8],
       [  1. , 193.2,  18.4,  65.7],
       [  1. ,  76.3,  27.5,  16. ],
       [  1. , 110.7,  40.6,  63.2],
       [  1. ,  88.3,  25.5,  73.4],
       [  1. , 109.8,  47.8,  51.4],
       [  1. , 134.3,   4.9,   9.3],
       [  1. ,  28.6,   1.5,  33. ],
       [  1. , 217.7,  33.5,  59. ],
       [  1. , 250.9,  36.5,  72.3],
       [  1. , 107.4,  14. ,  10.9],
       [  1. , 163.3,  31.6,  52.9],
       [  1. , 197.6,   3.5,   5.9],
       [  1. , 184.9,  21. ,  22. ],
       [  1. , 289.7,  42.3,  51.2],
       [  1. , 135.2,  41.7,  45.9],
       [  1. , 222.4,   4.3,  49.8],
       [  1. , 296.4,  36.3, 100.9],
       [  1. , 280.2,  10.1,  21.4],
       [  1. , 187.9,  17.2,  17.9],
       [  1. , 238.2,  34.3,   5.3],
       [  1. , 137.9,  46.4,  59. ],
       [  1. ,  25. ,  11. ,  29.7],
       [  1. ,  90.4,   0.3,  23.2],
       [  1. ,  13.1,   0.4,  25.6],
       [  1. , 255.4,  26.9,   5.5],
       [  1. , 225.8,   8.2,  56.5],
       [  1. , 241.7,  38. ,  23.2],
       [  1. , 175.7,  15.4,   2.4],
       [  1. , 209.6,  20.6,  10.7],
       [  1. ,  78.2,  46.8,  34.5],
       [  1. ,  75.1,  35. ,  52.7],
       [  1. , 139.2,  14.3,  25.6],
       [  1. ,  76.4,   0.8,  14.8],
       [  1. , 125.7,  36.9,  79.2],
       [  1. ,  19.4,  16. ,  22.3],
       [  1. , 141.3,  26.8,  46.2],
       [  1. ,  18.8,  21.7,  50.4],
       [  1. , 224. ,   2.4,  15.6],
       [  1. , 123.1,  34.6,  12.4],
       [  1. , 229.5,  32.3,  74.2],
       [  1. ,  87.2,  11.8,  25.9],
       [  1. ,   7.8,  38.9,  50.6],
       [  1. ,  80.2,   0. ,   9.2],
       [  1. , 220.3,  49. ,   3.2],
       [  1. ,  59.6,  12. ,  43.1],
       [  1. ,   0.7,  39.6,   8.7],
       [  1. , 265.2,   2.9,  43. ],
       [  1. ,   8.4,  27.2,   2.1],
       [  1. , 219.8,  33.5,  45.1],
       [  1. ,  36.9,  38.6,  65.6],
       [  1. ,  48.3,  47. ,   8.5],
       [  1. ,  25.6,  39. ,   9.3],
       [  1. , 273.7,  28.9,  59.7],
       [  1. ,  43. ,  25.9,  20.5],
       [  1. , 184.9,  43.9,   1.7],
       [  1. ,  73.4,  17. ,  12.9],
       [  1. , 193.7,  35.4,  75.6],
       [  1. , 220.5,  33.2,  37.9],
       [  1. , 104.6,   5.7,  34.4],
       [  1. ,  96.2,  14.8,  38.9],
       [  1. , 140.3,   1.9,   9. ],
       [  1. , 240.1,   7.3,   8.7],
       [  1. , 243.2,  49. ,  44.3],
       [  1. ,  38. ,  40.3,  11.9],
       [  1. ,  44.7,  25.8,  20.6],
       [  1. , 280.7,  13.9,  37. ],
       [  1. , 121. ,   8.4,  48.7],
       [  1. , 197.6,  23.3,  14.2],
       [  1. , 171.3,  39.7,  37.7],
       [  1. , 187.8,  21.1,   9.5],
       [  1. ,   4.1,  11.6,   5.7],
       [  1. ,  93.9,  43.5,  50.5],
       [  1. , 149.8,   1.3,  24.3],
       [  1. ,  11.7,  36.9,  45.2],
       [  1. , 131.7,  18.4,  34.6],
       [  1. , 172.5,  18.1,  30.7],
       [  1. ,  85.7,  35.8,  49.3],
       [  1. , 188.4,  18.1,  25.6],
       [  1. , 163.5,  36.8,   7.4],
       [  1. , 117.2,  14.7,   5.4],
       [  1. , 234.5,   3.4,  84.8],
       [  1. ,  17.9,  37.6,  21.6],
       [  1. , 206.8,   5.2,  19.4],
       [  1. , 215.4,  23.6,  57.6],
       [  1. , 284.3,  10.6,   6.4],
       [  1. ,  50. ,  11.6,  18.4],
       [  1. , 164.5,  20.9,  47.4],
       [  1. ,  19.6,  20.1,  17. ],
       [  1. , 168.4,   7.1,  12.8],
       [  1. , 222.4,   3.4,  13.1],
       [  1. , 276.9,  48.9,  41.8],
       [  1. , 248.4,  30.2,  20.3],
       [  1. , 170.2,   7.8,  35.2],
       [  1. , 276.7,   2.3,  23.7],
       [  1. , 165.6,  10. ,  17.6],
       [  1. , 156.6,   2.6,   8.3],
       [  1. , 218.5,   5.4,  27.4],
       [  1. ,  56.2,   5.7,  29.7],
       [  1. , 287.6,  43. ,  71.8],
       [  1. , 253.8,  21.3,  30. ],
       [  1. , 205. ,  45.1,  19.6],
       [  1. , 139.5,   2.1,  26.6],
       [  1. , 191.1,  28.7,  18.2],
       [  1. , 286. ,  13.9,   3.7],
       [  1. ,  18.7,  12.1,  23.4],
       [  1. ,  39.5,  41.1,   5.8],
       [  1. ,  75.5,  10.8,   6. ],
       [  1. ,  17.2,   4.1,  31.6],
       [  1. , 166.8,  42. ,   3.6],
       [  1. , 149.7,  35.6,   6. ],
       [  1. ,  38.2,   3.7,  13.8],
       [  1. ,  94.2,   4.9,   8.1],
       [  1. , 177. ,   9.3,   6.4],
       [  1. , 283.6,  42. ,  66.2],
       [  1. , 232.1,   8.6,   8.7]])

In [23]:
w_hat = np.linalg.inv(X.T@X)@X.T@np.array(y)

In [24]:
w_hat

array([ 2.93888937e+00,  4.57646455e-02,  1.88530017e-01, -1.03749304e-03])

In [25]:
y_pred = X@w_hat

In [26]:
y_pred

array([20.52397441, 12.33785482, 12.30767078, 17.59782951, 13.18867186,
       12.47834763, 11.72975995, 12.12295317,  3.72734086, 12.55084872,
        7.0322992 , 17.28512918, 10.57712073,  8.82630048, 18.43436638,
       20.81929952, 12.82365674, 23.22495716,  9.95168206, 14.16607293,
       18.10076728, 14.7405382 ,  6.4891503 , 16.5459329 ,  8.14651887,
       15.6100386 , 14.98951429, 17.05167344, 19.41053803,  9.14402389,
       21.6339338 , 11.3460929 ,  7.63888314, 18.86426829,  7.57483051,
       17.00682618, 23.40590052, 15.62347779,  9.90868103, 20.44761039,
       16.37766467, 17.2959832 , 21.59580326, 13.96385684,  8.88787996,
       15.16152314,  8.87338673, 21.7226299 , 16.26362018,  8.1681656 ,
       12.63121132,  9.33981296, 20.66297563, 19.94469957, 20.37443008,
       21.2926106 ,  8.52771254, 12.77458802, 21.89805198, 18.13348698,
        5.74215558, 22.89067208, 16.78426073, 13.21069202, 16.97773556,
        7.84904532,  9.01603163, 12.0370073 , 18.97657924, 21.10891244,
       17.77949782, 10.62693815, 10.36684881,  9.90298206, 17.32931197,
       11.85832174,  4.47758904, 13.81190223,  8.81331353,  9.67530328,
       11.44592364, 14.64794093, 10.17840799, 14.42184212, 20.78136464,
       15.18140789, 11.59870739, 15.59378475, 11.71127101, 16.92225511,
        9.99922965,  4.49631598, 19.15639616, 21.22757378, 10.48212385,
       16.31492112, 12.63571716, 15.33707782, 24.11860723, 16.94035021,
       13.87595844, 23.24248685, 17.64409385, 14.76221142, 20.30110878,
       17.93641467,  6.12602215,  7.10850249,  3.58725841, 19.69293106,
       14.7598741 , 21.14027498, 13.88060985, 16.40377623, 15.30509593,
       12.91968895, 11.97874744,  6.5707774 , 15.56609348,  6.82006767,
       14.41010605,  7.83807642, 13.6264571 , 15.0827909 , 19.45441306,
        9.12734958, 10.57717411,  6.599669  , 22.25549161,  7.88410649,
       10.4276871 , 15.57779819,  8.44915012, 19.26692307, 11.8368039 ,
       14.00141385, 11.45348627, 20.85125198,  9.76842795, 19.67547632,
        9.48964097, 18.39902932, 19.24986927,  8.76480262, 10.09133403,
        9.70853872, 15.29422368, 23.26086103, 12.26335941,  9.8272711 ,
       18.36720534, 10.0095377 , 16.3600003 , 18.22390132, 15.50161696,
        5.3075589 , 15.38485192, 10.0143112 , 10.38419866, 12.39914823,
       14.21383298, 13.55914568, 14.94678206, 17.35163608, 11.0682946 ,
       14.22372138, 10.82439531, 13.36324677, 17.1861428 , 17.9415563 ,
        7.39497997, 14.35827373,  7.60769238, 11.97093887, 13.74435742,
       24.78687031, 19.9793727 , 12.1620464 , 16.01099722, 12.38455495,
       10.5871997 , 13.92809918,  6.55467   , 24.13310013, 18.53852096,
       20.80301059,  9.69137313, 17.07644223, 18.64430648,  6.05162411,
       12.4891591 ,  8.42401933,  4.46622956, 18.48695797, 16.49530044,
        5.37034248,  8.16531236, 12.78592082, 23.76732149, 15.17319554])

In [31]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [39]:
from sklearn.metrics import mean_squared_error

def rmse(y_test, y_pred):
    return np.sqrt(mean_squared_error(y_test, y_pred))

In [40]:
rmse(y, y_pred)

np.float64(1.6685701407225697)

In [41]:
from sklearn.metrics import r2_score

In [42]:
r2_score(y, y_pred)

0.8972106381789522

**С заменой обратной матрицы на псевдо-обратну.**

In [51]:
w_hat_pinv = np.linalg.pinv(X.T@X)@X.T@np.array(y)

In [52]:
y_pred_pinv = X@w_hat_pinv

In [53]:
rmse(y, y_pred_pinv)

np.float64(1.6685701407225697)

In [54]:
r2_score(y, y_pred_pinv)

0.8972106381789522

**С помощью готовой библиотеки.**

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
model = LinearRegression()
model.fit(X, y)
y_pred1 = model.predict(X)

In [48]:
rmse(y, y_pred1)

np.float64(1.6685701407225697)

In [49]:
r2_score(y, y_pred1)

0.8972106381789522

**Вывод:**

Прогностическая модель во всех трех случаях дала одинаковые цифры результата и одинаково высокий результат прогнозирования.

Средняя ошибка прогнозирования составляет 1.6685 и 89.7% случаев модель может объяснить.